/**
 * Created by Jincheng on 2017/6/15.
 */
var applyingData = [
  { id: 1,
    activity_name: '10.18号，新街口春饼店开业，需要鼓手歌手各3名。',
    release_time: '8小时前',
    lasting_time: '10.18-10.19',
    event_location: '新街口商区',
    jobs: '主持',
    price: '800',
    unit: 'person',
    step: 1},
  { id: 2,
    activity_name: '10.19号，钟灵街店庆活动，需要主持、歌手各3名。',
    release_time: '9小时前',
    lasting_time: '10.18-10.19',
    event_location: '钟灵街商区',
    jobs: '歌手',
    price: '900',
    unit: 'person',
    step: 2},
  { id: 3,
    activity_name: '10.20号，下马坊促销活动，需要主持1名，演员2名。',
    release_time: '10小时前',
    lasting_time: '10.18-10.19',
    event_location: '下马坊商区',
    jobs: '主持',
    price: '750',
    unit: 'group',
    step: 2},
  { id: 4,
    activity_name: '10.21号，湖南路活动，需要鼓手歌手各3名。',
    release_time: '11小时前',
    lasting_time: '10.18-10.19',
    event_location: '湖南路商区',
    jobs: '歌手',
    price: '700',
    unit: 'group',
    step: 1},
  { id: 5,
    activity_name: '10.22号，上海路活动，需要鼓手歌手各3名。',
    release_time: '12小时前',
    lasting_time: '10.18-10.19',
    event_location: '上海路商区',
    jobs: '歌手',
    price: '850',
    unit: 'person',
    step: 3},
  { id: 6,
    activity_name: '10.23号，，鼓楼区活动，需要鼓手歌手各3名。',
    release_time: '13小时前',
    lasting_time: '10.18-10.19',
    event_location: '鼓楼区',
    jobs: '歌手',
    price: '1000',
    unit: 'group',
    step: 1}
]

var detailActivity = {
  id: 1,
  acivity_name: '10.23号，，鼓楼区活动，需要鼓手歌手各3名。',
  release_time: '',
  company: '',
  authen: true,
  activity_time: '',
  gather_time: '',
  gather_location: '',
  activity_detail: '',
  contact: '',
  occupations: []
}

export {applyingData, detailActivity}
